import type { ToolDefinition } from './types';

const VERIFIED_ON = '2026-09-20';

/**
 * The GitDeck tool registry.
 *
 * Every entry here was reachable and produced the expected page on
 * `verifiedAt`. See `docs/tools.md` for the verification method and for the
 * tools that were considered and rejected.
 */
export const TOOLS: readonly ToolDefinition[] = [
  {
    id: 'github-dev',
    name: 'GitHub.dev',
    description: 'Open the repository in a browser-based VS Code editor.',
    category: 'ide',
    urlTemplate: 'https://github.dev/{owner}/{repo}',
    website: 'https://github.dev',
    docsUrl: 'https://docs.github.com/en/codespaces/the-githubdev-web-based-editor',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
    icon: 'gh',
  },
  {
    id: 'github1s',
    name: 'GitHub1s',
    description: 'Read the repository in a fast, read-only VS Code view.',
    category: 'ide',
    urlTemplate: 'https://github1s.com/{owner}/{repo}',
    website: 'https://github1s.com',
    docsUrl: 'https://github.com/conwnet/github1s',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
    icon: '1s',
  },
  {
    id: 'stackblitz',
    name: 'StackBlitz',
    description: 'Run the project in an in-browser Node environment.',
    category: 'ide',
    urlTemplate: 'https://stackblitz.com/github/{owner}/{repo}',
    website: 'https://stackblitz.com',
    docsUrl: 'https://developer.stackblitz.com/guides/integration/open-from-github',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
    notes: 'Works best for JavaScript and TypeScript projects.',
    icon: 'sb',
  },
  {
    id: 'bolt-new',
    name: 'Bolt',
    description: 'Import the repository into an AI-assisted web IDE.',
    category: 'ide',
    urlTemplate: 'https://bolt.new/~/github.com/{owner}/{repo}',
    website: 'https://bolt.new',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
    icon: 'bo',
  },
  {
    id: 'github-codespaces',
    name: 'Codespaces',
    description: 'Create a cloud development environment for the repository.',
    category: 'ide',
    urlTemplate: 'https://github.com/codespaces/new?repo={owner}%2F{repo}',
    website: 'https://github.com/features/codespaces',
    docsUrl: 'https://docs.github.com/en/codespaces',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
    notes: 'Requires a signed-in GitHub account.',
    icon: 'cs',
  },
  {
    id: 'deepwiki',
    name: 'DeepWiki',
    description: 'Read a generated wiki explaining the codebase.',
    category: 'understand',
    urlTemplate: 'https://deepwiki.com/{owner}/{repo}',
    website: 'https://deepwiki.com',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
    icon: 'dw',
  },
  {
    id: 'gitdiagram',
    name: 'GitDiagram',
    description: 'Generate an interactive architecture diagram of the repository.',
    category: 'visualise',
    urlTemplate: 'https://gitdiagram.com/{owner}/{repo}',
    website: 'https://gitdiagram.com',
    docsUrl: 'https://github.com/ahmedkhaleel2004/gitdiagram',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
    icon: 'gd',
  },
  {
    id: 'githistory',
    name: 'Git History',
    description: 'Play back the change history of the current file.',
    category: 'visualise',
    urlTemplate: 'https://github.githistory.xyz/{owner}/{repo}/blob/{ref}/{path|path}',
    website: 'https://githistory.xyz',
    docsUrl: 'https://github.com/pomber/git-history',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
    requires: ['ref', 'path'],
    icon: 'gh',
  },
  {
    id: 'gitingest',
    name: 'GitIngest',
    description: 'Turn the repository into a single prompt-friendly text digest.',
    category: 'ai-context',
    urlTemplate: 'https://gitingest.com/{owner}/{repo}',
    website: 'https://gitingest.com',
    docsUrl: 'https://github.com/coderamp-labs/gitingest',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
    icon: 'gi',
  },
  {
    id: 'gitmcp',
    name: 'GitMCP',
    description: 'Expose the repository to AI assistants as an MCP server.',
    category: 'ai-context',
    urlTemplate: 'https://gitmcp.io/{owner}/{repo}',
    website: 'https://gitmcp.io',
    docsUrl: 'https://github.com/idosal/git-mcp',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
    icon: 'mc',
  },
  {
    id: 'ossinsight',
    name: 'OSS Insight',
    description: 'Inspect contributor, star and activity analytics.',
    category: 'insights',
    urlTemplate: 'https://ossinsight.io/analyze/{owner}/{repo}',
    website: 'https://ossinsight.io',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
    icon: 'oi',
  },
  {
    id: 'star-history',
    name: 'Star History',
    description: 'Chart how the repository gained stars over time.',
    category: 'insights',
    urlTemplate: 'https://www.star-history.com/#{owner}/{repo}',
    website: 'https://www.star-history.com',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
    icon: 'sh',
  },
  {
    id: 'deps-dev',
    name: 'Open Source Insights',
    description: 'Explore the dependency graph and known advisories.',
    category: 'security',
    urlTemplate: 'https://deps.dev/project/github/{owner}%2F{repo}',
    website: 'https://deps.dev',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
    icon: 'dd',
  },
  {
    id: 'openssf-scorecard',
    name: 'OpenSSF Scorecard',
    description: 'Review automated supply-chain security checks.',
    category: 'security',
    urlTemplate: 'https://scorecard.dev/viewer/?uri=github.com/{owner}/{repo}',
    website: 'https://scorecard.dev',
    docsUrl: 'https://github.com/ossf/scorecard',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
    icon: 'sc',
  },
  {
    id: 'github-code-search',
    name: 'GitHub Code Search',
    description: 'Search the repository with GitHub code search syntax.',
    category: 'search',
    urlTemplate: 'https://github.com/search?q=repo%3A{owner}%2F{repo}&type=code',
    website: 'https://github.com/search',
    docsUrl: 'https://docs.github.com/en/search-github/github-code-search',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
    icon: 'cs',
  },
  {
    id: 'codesandbox',
    name: 'CodeSandbox',
    description: 'Open the project in a cloud development sandbox.',
    category: 'ide',
    urlTemplate: 'https://codesandbox.io/p/github/{owner}/{repo}',
    website: 'https://codesandbox.io',
    status: 'unverified',
    verifiedAt: VERIFIED_ON,
    notes: 'Bot protection returned HTTP 403 to the automated check; needs a manual re-check.',
    icon: 'cb',
  },
  {
    id: 'grep-app',
    name: 'Grep',
    description: 'Search the repository with regular expressions.',
    category: 'search',
    urlTemplate: 'https://grep.app/{owner}/{repo}',
    website: 'https://grep.app',
    status: 'unverified',
    verifiedAt: VERIFIED_ON,
    notes: 'Rate limiting returned HTTP 429 to the automated check; needs a manual re-check.',
    icon: 'gr',
  },
];
