import type { ToolDefinition } from './types';

const VERIFIED_ON = '2026-09-20';

/**
 * The GitDeck tool registry.
 *
 * Every entry here was reachable and produced the expected page on
 * `verifiedAt`. See `docs/tools.md` for the verification method and for the
 * tools that were considered and rejected.
 *
 * One tool per job. Where two services do the same thing, the registry carries
 * the one that needs least from the user — no account, no credits, no sign-in —
 * and `docs/tools.md` records which alternative lost and why. A deck that
 * offers three ways to do the same thing makes the user do the choosing.
 */
export const TOOLS: readonly ToolDefinition[] = [
  {
    id: 'github-dev',
    name: 'Browse in VS Code',
    brand: 'GitHub.dev',
    description: 'Open the repository in a browser-based VS Code editor.',
    category: 'ide',
    urlTemplate: 'https://github.dev/{owner}/{repo}',
    website: 'https://github.dev',
    docsUrl: 'https://docs.github.com/en/codespaces/the-githubdev-web-based-editor',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
  },
  {
    id: 'stackblitz',
    name: 'Run it in the browser',
    brand: 'StackBlitz',
    description: 'Run the project in an in-browser Node environment.',
    category: 'ide',
    urlTemplate: 'https://stackblitz.com/github/{owner}/{repo}',
    website: 'https://stackblitz.com',
    docsUrl: 'https://developer.stackblitz.com/guides/integration/open-from-github',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
    notes: 'Works best for JavaScript and TypeScript projects.',
  },
  {
    id: 'github-codespaces',
    name: 'Start a cloud dev environment',
    brand: 'Codespaces',
    description: 'Create a cloud development environment for the repository.',
    category: 'ide',
    urlTemplate: 'https://github.com/codespaces/new?repo={owner}%2F{repo}',
    website: 'https://github.com/features/codespaces',
    docsUrl: 'https://docs.github.com/en/codespaces',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
    notes: 'Requires a signed-in GitHub account.',
  },
  {
    id: 'deepwiki',
    name: 'Read a generated wiki',
    brand: 'DeepWiki',
    description: 'Read a generated wiki explaining the codebase.',
    category: 'understand',
    urlTemplate: 'https://deepwiki.com/{owner}/{repo}',
    website: 'https://deepwiki.com',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
  },
  {
    id: 'gitdiagram',
    name: 'Diagram the architecture',
    brand: 'GitDiagram',
    description: 'Generate an interactive architecture diagram of the repository.',
    category: 'visualise',
    urlTemplate: 'https://gitdiagram.com/{owner}/{repo}',
    website: 'https://gitdiagram.com',
    docsUrl: 'https://github.com/ahmedkhaleel2004/gitdiagram',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
  },
  {
    id: 'githistory',
    name: "Replay this file's history",
    brand: 'Git History',
    description: 'Play back the change history of the current file.',
    category: 'visualise',
    urlTemplate: 'https://github.githistory.xyz/{owner}/{repo}/blob/{ref}/{path|path}',
    website: 'https://githistory.xyz',
    docsUrl: 'https://github.com/pomber/git-history',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
    requires: ['ref', 'path'],
  },
  {
    id: 'gitingest',
    name: 'Flatten it for an LLM',
    brand: 'GitIngest',
    description: 'Turn the repository into a single prompt-friendly text digest.',
    category: 'ai-context',
    urlTemplate: 'https://gitingest.com/{owner}/{repo}',
    website: 'https://gitingest.com',
    docsUrl: 'https://github.com/coderamp-labs/gitingest',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
  },
  {
    id: 'gitmcp',
    name: 'Connect it to an AI assistant',
    brand: 'GitMCP',
    description: 'Expose the repository to AI assistants as an MCP server.',
    category: 'ai-context',
    urlTemplate: 'https://gitmcp.io/{owner}/{repo}',
    website: 'https://gitmcp.io',
    docsUrl: 'https://github.com/idosal/git-mcp',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
  },
  {
    id: 'ossinsight',
    name: 'See who contributes',
    brand: 'OSS Insight',
    description: 'Inspect contributor, star and activity analytics.',
    category: 'insights',
    urlTemplate: 'https://ossinsight.io/analyze/{owner}/{repo}',
    website: 'https://ossinsight.io',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
  },
  {
    id: 'star-history',
    name: 'Chart star growth',
    brand: 'Star History',
    description: 'Chart how the repository gained stars over time.',
    category: 'insights',
    urlTemplate: 'https://www.star-history.com/#{owner}/{repo}',
    website: 'https://www.star-history.com',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
  },
  {
    id: 'deps-dev',
    name: 'Check dependencies',
    brand: 'deps.dev',
    description: 'Explore the dependency graph and known advisories.',
    category: 'security',
    urlTemplate: 'https://deps.dev/project/github/{owner}%2F{repo}',
    website: 'https://deps.dev',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
  },
  {
    id: 'openssf-scorecard',
    name: 'Score its security practices',
    brand: 'OpenSSF Scorecard',
    description: 'Review automated supply-chain security checks.',
    category: 'security',
    urlTemplate: 'https://scorecard.dev/viewer/?uri=github.com/{owner}/{repo}',
    website: 'https://scorecard.dev',
    docsUrl: 'https://github.com/ossf/scorecard',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
  },
  {
    id: 'github-code-search',
    name: 'Search the code',
    brand: 'GitHub Code Search',
    description: 'Search the repository with GitHub code search syntax.',
    category: 'search',
    urlTemplate: 'https://github.com/search?q=repo%3A{owner}%2F{repo}&type=code',
    website: 'https://github.com/search',
    docsUrl: 'https://docs.github.com/en/search-github/github-code-search',
    status: 'verified',
    verifiedAt: VERIFIED_ON,
  },
];
